# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: SelfHostedWSL

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world
      
      kubectl create deployment selenium-hub --image selenium/hub:3.9.0 --port 4444
